# Generated by Django 3.0.3 on 2020-02-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='robot_voice_summary',
            field=models.BooleanField(default=True),
        ),
    ]
