# Generated by Django 3.0.3 on 2020-02-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_stone_robot_voice_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stone',
            name='summary',
            field=models.TextField(max_length=2000),
        ),
    ]
